### ISSUE TITLE
Multiple workspaces?

### ISSUE THREAD

**Issue by ethanhs** [haskellcamargo/sclack#10]
Hi, first off, awesome app. I am using it through the Windows Subsystem for Linux, and it works spectacularly!

I was hoping to use this with multiple workspaces, so I was wondering if that is/will be supported. I took a quick poke at the code but didn't see anything indicating this would work.

**Comment by waisbrot** [comment]
Slacks multiple workspaces aren't very strongly connected. I'd prefer to manage them myself by running a separate instance per workspace in a terminal multiplexer or multi-tab terminal or multiple desktop workspaces. There'd have to be a big improvement over how Slack GUI handles multiple workspaces to make it worthwhile as a feature IMO.

**Comment by haskellcamargo** [comment]
Implemented in #16. You can switch contexts running each instance at a time. If you use a single workspace token, nothing should change.
