### ISSUE TITLE
Shared Channels Break Everything

### ISSUE THREAD

**Issue by dill0wn** [haskellcamargo/sclack#108]
Repro steps:

Join a workspace that has at least one shared channel.

<img width="1218" alt="screen shot 2019-02-12 at 4 19 17 pm" src="https://user-images.githubusercontent.com/1267330/52668610-ff76b600-2ee1-11e9-813d-1b2f042c728b.png">
<img width="1667" alt="screen shot 2019-02-12 at 4 21 50 pm" src="https://user-images.githubusercontent.com/1267330/52668733-554b5e00-2ee2-11e9-95f5-75d1180caa39.png">
 
There are actually two different errors depending on whether you're in the "owner's" workspace or not. The above is if you are in the "owner's" workspace.

From a share-ee's workspace: 

<img width="1081" alt="screen shot 2019-02-12 at 4 25 12 pm" src="https://user-images.githubusercontent.com/1267330/52668915-d0ad0f80-2ee2-11e9-9c2c-da0400bab6e4.png">

**Comment by dill0wn** [comment]
#109

**Comment by dill0wn** [comment]
submitted pull request #109

**Comment by duynguyenhoang** [comment]
Fixed in https://github.com/haskellcamargo/sclack/pull/109
