### ISSUE TITLE
Optional storage of config.json in user home directory

### ISSUE THREAD

**Issue by Aylr** [haskellcamargo/sclack#117]
# Proposal

Given that a user has a config in `~/.sclack/config.json`
When the user runs `sclack` from any directory
Then sclack should try to load the config file from `~/.sclack/config.json` first. If that file does not exist sclack will default to loading config from the current working directory.

**Comment by Cj-bc** [comment]
Hello, I'm wondering why this issue was closed.
I think that's a good idea, that problem causes it difficult to make homebrew formula because we need `config.json` on pwd.
Perhaps did you find any way to solve this or something?
thanks
