### ISSUE TITLE
Missing icons on MacOS

### ISSUE THREAD

**Issue by ErykLoom** [haskellcamargo/sclack#123]
When using iTerm 2 there are only question marks instead of icons

**Comment by fpgamcu** [comment]
@ErykLoom please look here for the solution https://github.com/haskellcamargo/sclack#nerd-fonts

**Comment by theabhinavdas** [comment]
@ErykLoom use the specific Nerd Font provided in the README. Also note that though it's called the FiraCode Nerd Font, it installs on MacOS as **FuraCode Nerd Font**. So if you have the original FiraCode font, and mistakenly choose it, it will not work.
