### ISSUE TITLE
[GS]et Dynamically Colors from Themes

### ISSUE THREAD

**Issue by arthurhenrique** [haskellcamargo/sclack#17]
Get and set dynamically colors from themes pre stablished. 

I have used the Dracula Theme(Zeno Rocha) a lot, and I already configured my slack desktop to use it. 
Is this possible load from slack-api this colors theme and put as my default theme?

**Comment by haskellcamargo** [comment]
I don't know a Slack API endpoint that does that thing (I've searched before to do that, but I can reinvestigate). We have a way to write custom themes, however (check `sclack/themes.py`). I believe that it will not be so complex to change the palette dynamically.

**Comment by haskellcamargo** [comment]
@jared-w you can add the section `"colors": 16` to your `~/.sclack` file.
![2018-08-08-174857_1362x767_scrot](https://user-images.githubusercontent.com/7553006/43863526-5c4f8e26-9b33-11e8-88cb-4e1e11d3a236.png)
