### ISSUE TITLE
Documentation for install leads to errors

### ISSUE THREAD

**Issue by ChrisCallanJr** [haskellcamargo/sclack#25]
Hey there, this is small so I figured I would make an issue rather than a pull request. Your instructions for installation via `pip` can lead to some issues upon install. Specifically the line `pip install -r requirements.txt` should be `pip3 install -r requirements.txt` since Python 3.4+ is required. Otherwise, dependencies aren't properly installed.

**Comment by LukyVj** [comment]
Yeah I ran into a similar issue ( referenced here:https://github.com/haskellcamargo/sclack/issues/24  )

**Comment by haskellcamargo** [comment]
I've changed `pip` to `pip3` on README now. Thank you for reporting!
