### ISSUE TITLE
Error: "pile object does not support item assignment"

### ISSUE THREAD

**Issue by LukyVj** [haskellcamargo/sclack#26]
Whenever I try to access a channel I got this as a response: 
![](https://puu.sh/BaLA9/db736529e4.png)

**Comment by LukyVj** [comment]
I'm not sure how exactly I did that, but seems like I fixed it by checking the open PRs on this repo :)

**Comment by haskellcamargo** [comment]
It seems like a race condition. `go_to_channel` was called when the chatbox was still a `LoadingChatBox` instead of a `Chatbox`.
