### ISSUE TITLE
Contacts coming online doesn't appear to update the contact list

### ISSUE THREAD

**Issue by Garethp** [haskellcamargo/sclack#27]
I'm not sure if it's just because of a low polling rate or because it's not set to update, but after a contact came online their status in the side bar didn't update

**Comment by haskellcamargo** [comment]
There is no subscription for user status for now because they weren't working via Slack RTM the last time I've tried. It is still a TODO for us.
API reference: https://api.slack.com/events/presence_sub

**Comment by Garethp** [comment]
Thanks
