### ISSUE TITLE
Cannot see all users

### ISSUE THREAD

**Issue by LukyVj** [haskellcamargo/sclack#44]
Hello, it's me again! 

So as you may understand from the title, I'm working in a big-ush company with 200+ employees, and from the sidebar, on the direct messages part, I can only see like 15 people, and I'm unable to scroll nor to move the cursor further down, which disallow me to find other users.

**Comment by duynguyenhoang** [comment]
@LukyVj  please take a look at this PR https://github.com/haskellcamargo/sclack/pull/45

**Comment by haskellcamargo** [comment]
I'm also working on the quick switcher (<kbd>ctrl k</kbd>) in order to allow to pick any user/channel to chat.

**Comment by haskellcamargo** [comment]
Maybe this helps: #49

**Comment by duynguyenhoang** [comment]
Hi @LukyVj Could you please check master branch again whether we can close this issue?

**Comment by LukyVj** [comment]
All good :)

**Comment by duynguyenhoang** [comment]
Fixed in https://github.com/haskellcamargo/sclack/pull/49 and https://github.com/haskellcamargo/sclack/pull/45
