### ISSUE TITLE
Typing "q" while you write a message will close the app

### ISSUE THREAD

**Issue by hnb2** [haskellcamargo/sclack#5]
Hi there, I found a bug while trying out your code, here is what I did in order to reproduce it:

1. `./app.sh`
2. Setup my token
3. Client is loading
4. I select myself in the left column and type `enter`
5. Type `i` to enter insert mode
6. Type in order: `ytrewq`, the app closes right after I type `q`

I'm running Mac OsX with the default Terminal in a tmux session. Let me know if you need more info.

**Comment by J-Vaughan** [comment]
Haha this sounds like it would be something I'd miss in one of my projects

**Comment by haskellcamargo** [comment]
Thank you for reporting! Bugfixed! :beetle:
