### ISSUE TITLE
Up/Down key to switch between chatbox and message panel

### ISSUE THREAD

**Issue by tuandm** [haskellcamargo/sclack#53]
It would be convenient if we can easily switch between chatbox and message panel 
1. Pressing "Up" in chatbox will move cursor to message pane at the last message
2. Pressing "Down" from last message of message panel will move cursor to chatbox at the last char (insert mode)

**Comment by haskellcamargo** [comment]
Now implemented in the last version on `master`. Thank you for your feedback!

**Comment by tuandm** [comment]
@haskellcamargo Thanks for the quick action. I'm going to add some code, but you was so fast :).
