### ISSUE TITLE
Don't receive new messages until I reopen a window

### ISSUE THREAD

**Issue by block8437** [haskellcamargo/sclack#62]
Hey,

I noticed that when if I have a chat window open, I won't receive any new messages in that chat until I reopen the chat (by going to the sidebar and using enter the same chat window). I'm on the latest from master (at the time of writing, `326ad0385104c34207ff73bdd88dea416790a303`)

**Comment by block8437** [comment]
This includes messages that I send, they won't appear in the chat logs until I refresh the chat.

**Comment by duynguyenhoang** [comment]
Hi @block8437 Do you see any error message on the chat screen? Or any more detail to help us investigate the problem.

**Comment by block8437** [comment]
@duynguyenhoang my apologies for the vague description of the issue. Unfortunately there are no error messages that I could see in the error screen. It simply doesn't display new messages in the chat window. For example, if I send the slackbot something, I won't see my message or it's reply. If I then go to the side bar and click enter on slackbot again, it will refresh with my message and it's response.

**Comment by block8437** [comment]
I pulled from master and I no longer have this issue, so I'm going to close this for now.
