### ISSUE TITLE
Emojis rendering issues

### ISSUE THREAD

**Issue by hnb2** [haskellcamargo/sclack#8]
I'm not sure if there is a pattern or if it is a coincidence but seems like all emojis starting with a special character or a number are not being rendered:

<img width="288" alt="screen shot 2018-08-07 at 3 56 55 pm" src="https://user-images.githubusercontent.com/3678416/43774573-9b66b154-9a5a-11e8-9bb4-783f66545d80.png">

While all the others seems to be rendered properly, even the ones with a digit at the end (`clock9` for instance).

**Comment by haskellcamargo** [comment]
Thank you for reporting! The error was reproduced and fixed. It was being caused by a ill-formed regular expression in the markdown component.

**Comment by hnb2** [comment]
<img width="216" alt="screen shot 2018-08-07 at 4 33 15 pm" src="https://user-images.githubusercontent.com/3678416/43776003-a2225458-9a5f-11e8-992b-9d9dbc23feac.png">

I think the `:+1:` still does not pass

**Comment by arthurhenrique** [comment]
#13
