### ISSUE TITLE
Compilation fails (Linux)

### ISSUE THREAD

**Issue by ginsterbusch** [haskellcamargo/sclack#91]
Hi there,

thought I'd give this nifty looking piece of software a try .. but compilation fails.
As I'm not a crack in python, I don't know exactly what went wrong. 
Whenever I try running app.py (permissions set correctly), it fails with the following backtrace error message:
```
Traceback (most recent call last):
  File "./app.py", line 14, in <module>
    from sclack.components import Attachment, Channel, ChannelHeader, ChatBox, Dm
  File "/home/fwolf/inst/sources/sclack/sclack/components.py", line 11, in <module>
    from .markdown import MarkdownText
  File "/home/fwolf/inst/sources/sclack/sclack/markdown.py", line 3, in <module>
    from .store import Store
  File "/home/fwolf/inst/sources/sclack/sclack/store.py", line 1, in <module>
    from slackclient import SlackClient
  File "/usr/local/lib/python3.4/dist-packages/slackclient/__init__.py", line 1, in <module>
    from .client import SlackClient # noqa
  File "/usr/local/lib/python3.4/dist-packages/slackclient/client.py", line 7, in <module>
    from .server import Server
  File "/usr/local/lib/python3.4/dist-packages/slackclient/server.py", line 12, in <module>
    from requests.packages.urllib3.util.url import parse_url
ImportError: No module named 'requests.packages'
```

Environment:
- OS: Linux Mint 17.3 LTS (Ubuntu LTS support enabled)
- Platform: x86_64
- Python: 3.4

**Comment by duynguyenhoang** [comment]
Hi, 

Have you run `pip3 install -r requirements.txt` before?

More detail at https://github.com/haskellcamargo/sclack#from-source

**Comment by ginsterbusch** [comment]
Yep. I even went that far and installed the development requirements as well - to no afail. Still getting this error.

cu, w0lf.

**Comment by duynguyenhoang** [comment]
Could you please try to remove Mint (Ubuntu) python-urllib3 and install new urllib3, you can follow below command

```
apt-get remove python-urllib3
pip install urllib3
```

**Comment by ginsterbusch** [comment]
@duynguyenhoang Nope, that would lead to deinstalling of a lot of other libraries (including pip!), which probably is going to break some other programs, which then would lead to destabilize my main working environment.

Screenshot: http://gfx.fwwd.de/screenshots/synaptic_remove_urllib3.png

Thus I'd suggest adding **ANOTHER requirement** to the Readme / Docs: urllib3 of version x or higher ;)

Guess this nifty-looking toy is not gonna be mine (for now) :(

cu, w0lf.

**Comment by ginsterbusch** [comment]
@duynguyenhoang that would be quite awesome :)

cu, w0lf.

**Comment by ToxicBakery** [comment]
Using ubuntu 18.04 the requirements install fine with python3/pip3 installed.

**Comment by duynguyenhoang** [comment]
@ginsterbusch ,

I have tried to instal Mint17.3, and everything works fine.

Could you try to install requrement with `--user`?
``` pip3 install -r requirements.txt  --user```

Here is my Mint version: https://i.imgur.com/ofYh6Vb.png

**Comment by ginsterbusch** [comment]
Hi, my Mint version is 14.04.5, but that should make no difference.
pip3 says, that all requirements are already met. 

After a bit of reading up, I tried this one instead:

`pip3 install -r requirements.txt --user --ignore-installed`

And behold! Now it works! :)
I'd strongly suggest adding this info to the source compilation data :)

cu, w0lf.
